version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
  pre_build:
    commands:
      # - echo "Installing dependencies..."
      # - echo "Performing Trivy file scan before building the image..."
      # - wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.tar.gz
      # - tar zxvf trivy_0.19.2_Linux-64bit.tar.gz
      # - export PATH=$PATH:$PWD
      # - trivy filesystem --exit-code 0 --no-progress . >> trivyfilescan.txt
      # - echo "Downloading and installing OWASP Dependency-Check..."
      # - wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.0.2/dependency-check-7.0.2-release.zip
      # - unzip dependency-check-7.0.2-release.zip
      - echo "Installing SonarQube Scanner"
      - curl -o sonar-scanner-cli.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip sonar-scanner-cli.zip
  build:
    commands:
      # - echo "Running tests..."
      # - echo "Building Docker image..."
      # - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      # - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/amazon:latest" .
      # - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/amazon:latest"
  post_build:
    commands:
      # - echo "Performing Trivy image scan after building the image..."
      # - trivy image  "$DOCKER_REGISTRY_USERNAME/amazon:latest" >> trivyimage.txt
      # - echo "Running OWASP Dependency-Check scan..."
      # - cd dependency-check/bin
      # - ./dependency-check.sh --scan . --format ALL
      # - echo "Build completed successfully!"
      - echo "Running SonarQube analysis"
      - ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner \
          -Dsonar.host.url=http://15.206.145.132:9000 \
          -Dsonar.login=sqp_a4cb38492c16347df742c7976b6ed38e66f71f98 \
          -Dsonar.projectKey=Amazon \
          -Dsonar.sources=.
artifacts:
  files:
    - '**/*'