version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /cicd/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /cicd/docker-credentials/password
    DOCKER_REGISTRY_URL: /cicd/docker-registry/url
phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - echo "Performing Trivy file scan before building the image..."
      - wget https://github.com/aquasecurity/trivy/releases/download/v0.19.2/trivy_0.19.2_Linux-64bit.tar.gz
      - tar zxvf trivy_0.19.2_Linux-64bit.tar.gz
      - export PATH=$PATH:$PWD
      - trivy filesystem --exit-code 0 --no-progress .
  build:
    commands:
      - echo "Running tests..."
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/amazon:latest" .
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/amazon:latest"
  post_build:
    commands:
      - echo "Performing Trivy image scan after building the image..."
      - trivy image  "$DOCKER_REGISTRY_USERNAME/amazon:latest"
      - echo "Build completed successfully!"
artifacts:
  files:
    - '**/*'